automountServiceAccountToken: false
priorityClassName: system-node-critical

image:
  repository: nethermindeth/eks-nvme-ssd-provisioner
  pullPolicy: IfNotPresent
  tag: v1.0.1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

securityContext: 
  privileged: true

nodeSelector:
  aws.amazon.com/eks-local-ssd: "true"

tolerations: []

affinity: {}
